// Code generated by Wire. DO NOT EDIT.

package registry

import (
	"github.com/go-micro/microwire/v5/util/generic"
)

var Plugins = generic.NewContainer(func(opts ...Option) Registry { return nil })
