// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package micro

import (
	"github.com/go-micro/microwire/v5/broker"
	"github.com/go-micro/microwire/v5/cli"
	"github.com/go-micro/microwire/v5/config/configdi"
	"github.com/go-micro/microwire/v5/registry"
	"github.com/go-micro/microwire/v5/store"
	"github.com/go-micro/microwire/v5/transport"
)

// Injectors from wire.go:

func newService(options *Options, cliConfig *cli.Config, brokerConfig *broker.Config, registryConfig *registry.Config, storeConfig *store.Config, transportConfig *transport.Config) (Service, error) {
	cliCli, err := cli.ProvideCli(cliConfig)
	if err != nil {
		return nil, err
	}
	diFlags, err := broker.ProvideFlags(brokerConfig, cliConfig, cliCli)
	if err != nil {
		return nil, err
	}
	registryDiFlags, err := registry.ProvideFlags(registryConfig, cliConfig, cliCli)
	if err != nil {
		return nil, err
	}
	storeDiFlags, err := store.ProvideFlags(storeConfig, cliConfig, cliCli)
	if err != nil {
		return nil, err
	}
	transportDiFlags, err := transport.ProvideFlags(transportConfig, cliConfig, cliCli)
	if err != nil {
		return nil, err
	}
	diDiFlags, err := ProvideFlags(diFlags, registryDiFlags, storeDiFlags, transportDiFlags)
	if err != nil {
		return nil, err
	}
	diParsed, err := cli.ProvideParsed(cliConfig, cliCli)
	if err != nil {
		return nil, err
	}
	diConfig, err := cli.ProvideConfig(diDiFlags, diParsed, cliConfig)
	if err != nil {
		return nil, err
	}
	config, err := configdi.ProvideConfigor(diConfig)
	if err != nil {
		return nil, err
	}
	brokerDiConfig, err := broker.ProvideConfig(diConfig, diFlags, brokerConfig, cliConfig, config)
	if err != nil {
		return nil, err
	}
	brokerBroker, err := broker.Provide(brokerDiConfig, brokerConfig)
	if err != nil {
		return nil, err
	}
	registryDiConfig, err := registry.ProvideConfig(diConfig, registryDiFlags, registryConfig, cliConfig, config)
	if err != nil {
		return nil, err
	}
	registryRegistry, err := registry.Provide(registryDiConfig, registryConfig)
	if err != nil {
		return nil, err
	}
	storeDiConfig, err := store.ProvideConfig(diConfig, storeDiFlags, storeConfig, cliConfig, config)
	if err != nil {
		return nil, err
	}
	storeStore, err := store.Provide(storeDiConfig, storeConfig)
	if err != nil {
		return nil, err
	}
	transportDiConfig, err := transport.ProvideConfig(diConfig, transportDiFlags, transportConfig, cliConfig, config)
	if err != nil {
		return nil, err
	}
	transportTransport, err := transport.Provide(transportDiConfig, transportConfig)
	if err != nil {
		return nil, err
	}
	microService, err := ProvideAllService(options, brokerBroker, registryRegistry, storeStore, transportTransport)
	if err != nil {
		return nil, err
	}
	return microService, nil
}
