// Code generated by Wire. DO NOT EDIT.

package transport

import (
	"github.com/go-micro/microwire/v5/util/generic"
)

var Plugins = generic.NewContainer(func(opts ...Option) Transport { return nil })
